### ISSUE TITLE
Error: Must be run on OSX

### ISSUE THREAD

**Issue by chrisanderss0n** [mongodb-js/electron-installer-dmg#1]
I have tried running running this package on Heroku, and got the following error:

Error: Must be run on OSX

Possible to support making DMG's when on another OS?

**Comment by kangas** [comment]
Hi @chrisanderss0n, sorry that I didn't see the issue you created until just now.

electron-installer-dmg wraps https://www.npmjs.com/package/appdmg which presently only works on OS X. It invokes several applications that only exist on OS X, including hdiutil and SetFile.

If you're curious about what it would take to implement a cross-platform toolchain to build .dmg files, see https://github.com/LinusU/node-appdmg/issues/14
