### ISSUE TITLE
DMG Background Image Doesn't Show

### ISSUE THREAD

**Issue by hoffmabc** [mongodb-js/electron-installer-dmg#2]
It doesn't seem like PNG backgrounds are working properly.

**Comment by kangas** [comment]
Hi @hoffmabc, can you provide more details? It's working well for us currently on OS X 10.10. The most recent .dmg I built & tested was two days ago.

electron-installer-dmg wraps https://www.npmjs.com/package/appdmg so all of its guidance on background images, including Retina background images, should still apply. It has to turn PNG images into TIFF files so the Finder can read them.

**Comment by imlucas** [comment]
Closing as there's been no response and not enough info to attempt a repro.
