### ISSUE TITLE
dmg isn't compressed

### ISSUE THREAD

**Issue by cruzerld** [mongodb-js/electron-installer-dmg#8]
the appdmg spec has this:

`
format (enum[string], optional) - Disk image format
UDRW - UDIF read/write image
UDRO - UDIF read-only image
UDCO - UDIF ADC-compressed image
UDZO - UDIF zlib-compressed image
UDBZ - UDIF bzip2-compressed image (OS X 10.4+ only)
ULFO - UDIF lzfse-compressed image (OS X 10.11+ only)
`

Can this be added in to this package? It would save about 10-15% space in my project's dmg, and I'd rather use this package than appdmg directly.

**Comment by imlucas** [comment]
@cruzerld Ah I see. Let me give it a try

**Comment by imlucas** [comment]
@cruzerld Done.  See #10 for details.  I would be quite to curious to hear about your results.  Perhaps you could post results back here?

**Comment by cruzerld** [comment]
Hey, sorry for getting back to you late. Seems to have worked. My .dmg went from 55MB to 50MB by using UDBZ. Thanks!
